#pragma once

namespace MonsterEnums {

enum class Type {
   HUMANOID,
   ABERRATION,
   DRAGON,
   FIEND,
   UNDEAD,
   MONSTROSITY,
   ELEMENTAL,
   FEY,
   CONSTRUCT,
   PLANT,
   BEAST,
   TITAN,
   SHAPECHANGER
};

enum class Size { TINY, SMALL, MEDIUM, LARGE, HUGEs, GARGANTUAN };

enum class Align {
   LAWFULGOOD,
   NEUTRALGOOD,
   CHAOTICGOOD,
   ANYALIGNMENT,
   ANYNONGOODALIGNMENT,
   ANYNONLAWFULALIGNMENT,
   LAWFULNEUTRAL,
   NEUTRAL,
   CHAOTICNEUTRAL,
   LAWFULEVIL,
   NEUTRALEVIL,
   CHAOTICEVIL,
   UNALIGNED
};

};  // namespace MonsterEnums
